#!/usr/bin/env bash
# transfers a file from our client to a server:
if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

#Assing the argunments to variables
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

#transfer the file using secure copy protocol (scp)
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip":~
