#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get -y update
apt-get -y install nginx
HOSTNAME=$(hostname)
cat<<EOF > /etc/nginx/sites-available/default
server {
	listen 80 default_server
	listen [::]:80 default_server;

	# Other nginx configuration settings...

	location / {
		add_header X-served-By $HOSTNAME;
	}
}
EOF

systemcl restart nginx

exit 0
