#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
apt-get -y update
apt-get -y install nginx
HOSTNAME=$(hostname)
cat <<EOF > /etc/nginx/sites-available/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # Other nginx configuration settings...

        location / {
                add_header X-Served-By $HOSTNAME;
        }
}
EOF
systemtcl restart nginx

exit 0
