#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get install -y haproxy=2.6.\*




echo "
frontend  kim-kimtai-frontend
        bind *:80
        mode http
        default_backend kim-kimtai-backend
backend kim-kimtai-backend
        balance roundrobin
        server web-01 100.25.10.201:80 check
        server web-02 100.25.10.202:80 check
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

service haproxy start
~                      
