#!/bin/bash env
# script that set up a few firewall rules on web-01
sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw disable
sudo ufw enable

