#!/usr/bin/env bash
#stop the running Nginx service
service nginx stop
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen [0-9]*;/listen 8080;/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
